module.exports = {
  publicRuntimeConfig: {
    SENTRY_PUBLIC_DSN: process.env.SENTRY_PUBLIC_DSN,
    AWS_APPSYNC_GRAPHQL_ENDPOINT: process.env.AWS_APPSYNC_GRAPHQL_ENDPOINT,
    AWS_APPSYNC_AUTHENTICATION_TYPE: process.env.AWS_APPSYNC_AUTHENTICATION_TYPE,
    AWS_APPSYNC_REGION: process.env.AWS_APPSYNC_REGION,
    AWS_APPSYNC_APIKEY: process.env.AWS_APPSYNC_APIKEY,
  }
}
